Incluído README.md
jalexandrevm/python_codarme pull request #1
Opened 2022-03-09 14:32 UTC by jalexandrevm

Adicionado resumo em README.md do módulo 12

Aprendendo e testando sobre o PULL REQUEST

Se puderem ajudar, queria ver o funcionamento dos comentários e propostas

Valeu a ajuda pessoal

2022-03-09 16:05 UTC, brunobertolini commented
Boa @jalexandrevm, parabéns pela sua primeira PR! 😃

Dica: tanto a descrição da PR quanto os comentários **aceitam markdown**!

2022-03-09 16:43 UTC, jalexandrevm commented
> Boa @jalexandrevm, parabéns pela sua primeira PR! 😃
> 
> Dica: tanto a descrição da PR quanto os comentários **aceitam markdown**!

Valeu Bruno, anotado e já vou testar nas próximas 

Acabei de instalar o GitHub _mobile_ pra testar nas diferentes plataformas também 

Vou simular a partir da minha VM com **Ubuntu** como se fosse outra pessoa _contribuindo_ também 

Boa tarde

2022-03-09 21:08 UTC, SergioRSanchez commented
Boa tarde.

2022-03-10 17:09 UTC, gcrsaldanha commented
Parabéns pelo seu PR, @jalexandrevm ! 

Se quiser adicionar "reviewers" (revisores), você precisa adicionar as [pessoas como colaboradores](https://docs.github.com/pt/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository). E aí as pessoas que você adicionar vão aparecer quando vc selecionar "adicionar reviewers"

2022-03-10 17:10 UTC, gcrsaldanha commented on mod-12/README.md
> +   9. [Editar Evento Parcial (PATCH)](#exercícios)
Curti demais o índice!

2022-03-10 17:11 UTC, gcrsaldanha requested changes
Adicionei alguns comentários solicitando mudanças, só para você ver como aparece :)

2022-03-10 17:11 UTC, gcrsaldanha commented on mod-12/README.md
> +> > 2.caso haja `Scripts`, usar `source venv/Scripts/activate`
```suggestion
> > 1. se na `venv` tiver a pasta `bin`, ativamos com `source venv/bin/activate`
> >
> > 2. caso haja `Scripts`, usar `source venv/Scripts/activate`
```

2022-03-10 19:18 UTC, jalexandrevm commented on mod-12/README.md
> +   9. [Editar Evento Parcial (PATCH)](#exercícios)
Criei o _índice_ nos resumos dos primeiros módulos e vou copiando para os próximos
Coloco aqui e depois atualizo com as **referências corretas**
Ainda vou fazer isso, estou finalizando os vídeos do _módulo 12_ e vou incluindo enquanto assisto

2022-03-10 19:55 UTC, merged